Traceback (most recent call last):
  File "check_exec.py", line 166, in <module>
    main(sys.argv[i])
  File "check_exec.py", line 83, in main
    result = find_bounds_issues(line, argument)
  File "check_exec.py", line 94, in find_bounds_issues
    frontHalf, backHalf = line.split(variable, 1)
ValueError: empty separator
Traceback (most recent call last):
  File "check_exec.py", line 166, in <module>
    main(sys.argv[i])
  File "check_exec.py", line 83, in main
    result = find_bounds_issues(line, argument)
  File "check_exec.py", line 94, in find_bounds_issues
    frontHalf, backHalf = line.split(variable, 1)
ValueError: empty separator
Traceback (most recent call last):
  File "check_exec.py", line 166, in <module>
    main(sys.argv[i])
  File "check_exec.py", line 83, in main
    result = find_bounds_issues(line, argument)
  File "check_exec.py", line 94, in find_bounds_issues
    frontHalf, backHalf = line.split(variable, 1)
ValueError: empty separator
Traceback (most recent call last):
  File "check_exec.py", line 166, in <module>
    main(sys.argv[i])
  File "check_exec.py", line 83, in main
    result = find_bounds_issues(line, argument)
  File "check_exec.py", line 94, in find_bounds_issues
    frontHalf, backHalf = line.split(variable, 1)
ValueError: empty separator
Traceback (most recent call last):
  File "check_exec.py", line 166, in <module>
    main(sys.argv[i])
  File "check_exec.py", line 83, in main
    result = find_bounds_issues(line, argument)
  File "check_exec.py", line 94, in find_bounds_issues
    frontHalf, backHalf = line.split(variable, 1)
ValueError: empty separator
Traceback (most recent call last):
  File "check_exec.py", line 166, in <module>
    main(sys.argv[i])
  File "check_exec.py", line 33, in main
    for lineNum, line in enumerate(f):
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 2473: invalid start byte
